export const gujaratData = {
  "Ahmedabad": ["Ahmedabad City", "Bavla", "Daskroi", "Detroj-Rampura", "Dhandhuka", "Dholera", "Dholka", "Mandal", "Sanand", "Viramgam"],
  "Amreli": ["Amreli", "Bagasara", "Rajula", "jafrabad"],
  "Anand": ["Anand", "Borsad\nPetlad", "Tarapur", "Umreth\nKhambhat"],
  "Arvalli": ["Bhiloda", "Meghraj\nBayad", "Modasa"],
  "Banas Kantha": ["Bhabhar", "Deesa", "Palanpur"],
  "Bharuch": ["Amod", "Anklesvar", "Bharuch", "Hansot", "Jambusar", "Jhagadia", "Netrang", "Vagra", "Valia"],
  "Bhavnagar": ["Bhavnagar", "Gariadhar", "Ghogha", "Jesar", "Mahuva", "Palitana", "Sihor", "Talaja", "Umrala", "Vallabhipur"],
  "Botad": ["Barwala", "Botad", "Gadhada", "Ranpur"],
  "Chhota Udepur": ["Bodeli*", "Chhota Udepur", "Jetpur Pavi", "Kavant", "Nasvadi", "Sankheda"],
  "Devbhumi Dwarka": ["Bhanvad", "Kalyanpur", "Khambhalia"],
  "Dahod": ["Dahod", "Devgadbaria", "Dhanpur", "Fatepura", "Garbada", "Jhalod", "Limkheda", "Sanjeli", "Singvad"],
  "Gandhinagar": ["Dehgam", "Gandhinagar", "Kalol"],
  "Gir Somnath": ["Gir Gadhada", "Talala"],
  "jamnagar": ["Jamnagar", "Jodiya", "Lalpur"],
  "Junagadh": ["Bhesan", "Junagadh", "Junagadh City", "Mendarda"],
  "Kachchh": ["Anjar", "Gandhidham", "Lakhpat", "Mandvi", "Mundra", "Nakhatrana", "Rapar"],
  "Kheda": ["Galteshwar", "Kapadvanj", "Kheda", "Mahudha", "Matar", "Nadiad", "Vaso"],
  "Mehsana": ["Becharaji", "Jotana", "Kadi", "Kheralu", "Mehsana", "Satlasana", "Vadnagar"],
  "Mahisagar": ["Balasinor", "Kadana", "Khanpur", "Lunawada", "Santrampur", "Virpur"],
  "Morbi": ["Halvad", "Maliya", "Morbi", "Tankara", "Wankaner"],
  "Narmada": ["Dediapada", "Garudeshwar", "Nandod", "Sagbara", "Tilakwada"],
  "Navsari": ["Bansda", "Chikhli", "Gandevi", "Khergam", "Navsari"],
  "Panch Mahals": ["Ghoghamba", "Godhra", "Halol", "Jambughoda", "Kalol", "Morwa (Hadaf)", "Shehera"],
  "Patan": ["Chanasma", "Harij", "Patan", "Radhanpur", "Sami", "Santalpur", "Sarasvati", "Shankheshwar", "Sidhpur"],
  "Porbandar": ["Kutiyana"],
  "Rajkot": ["Jamkandorna", "Kotda Sangani", "Lodhika", "Paddhari", "Rajkot", "Vinchhiya"],
  "Sabar Kantha": ["Khedbrahma", "Poshina", "Vijaynagar"],
  "Surat": ["Chorasi", "Kamrej", "Mahuva", "Mangrol", "Olpad", "Palsana", "Surat City", "Umarpada"],
  "Surendranagar": ["Chotila", "Chuda", "Dasada", "Lakhtar", "Limbdi", "Muli", "Sayla", "Wadhwan"],
  "Tapi": ["Dolvan", "Kukarmunda", "Nizar", "Songadh", "Uchchhal", "Vyara"],
  "The Dangs": ["Aahva", "Subir", "Waghai"],
  "Vadodara": ["Desar", "Karjan", "Padra", "Savli", "Sinor", "Vadodara", "Vaghodia"],
  "Valsad": ["Dharampur", "Kaprada", "Pardi", "Umbergaon", "Valsad", "Vapi"]
}
