export const karnatakaData = {
  "Bengaluru (U)": ["Anekal", "Bengaluru (N)", "Bengaluru (S)", "Yelahanka", "Bengaluru (E)"],
  "Bengaluru (R)": ["Devanahalli", "Doddaballapura", "Hoskote", "Nelamangala"],
  "Bengaluru (S) (Ramanagara)": ["Magadi", "Harohalli", "Channapatna", "Ramanagara", "Kanakapura"],
  "Chitradurga": ["Holalkere", "Chitradurga", "Hiriyur", "Challakere", "Hosadurga", "Molkalmuru"],
  "Davanagere": ["Channagiri", "Davanagere", "Jagalur", "Harihar", "Honnali", "Nyamati"],
  "Chikkaballapura": ["Gudibande", "Chintamani", "Bagepalli", "Gowribidanur", "Chickaballapura", "Siddlaghatta", "Manchenahalli", "Cheluru"],
  "Kolar": ["Srinivasapura", "Kolar", "Bangarpet", "Malur", "KGF", "Mulbagal"],
  "Shivamogga": ["Soraba", "Shivamogga", "Sagar", "Bhadravathi", "Hosanagara", "Shikaripura", "ThirthahaIli"],
  "Tumakuru": ["Madhugiri", "Tumakur", "Turuvekere", "Kunigal", "Koratagere", "Sira", "Gubbi", "Tiptur", "Pavagada", "Chikkanayakanahalli"],
  "Chamarajanagar": ["Yelandur", "Gundlupet", "Hanur", "Chamarajanagar", "Kollegal"],
  "Chikkamagaluru": ["Mudigere", "Kadur", "Shringeri", "Chikkamagaluru", "Koppa", "Tarikere", "Ajjampur", "N R Pura", "Kalasa"],
  "Dakshina Kannada": ["Belthangadi", "Bantwal", "Puttur", "Moodbidri", "Sulya", "Mangaluru", "Ullal", "Mulki", "Kadaba"],
  "Hassan": ["Arakalgud", "Hassan", "Belur", "Arasikere", "Alur", "C R Patna", "H N Pura", "Sakleshpura"],
  "Kodagu": ["Madikeri", "Somwarpet", "Virajpet", "Ponnampete", "Kushalnagar"],
  "Mandya": ["Pandavapura", "Srirangapatna", "Nagamangala", "Mandya", "Malavalli", "Maddur", "K R Pet"],
  "Mysuru": ["K R Nagara", "Nanjangud", "Hunsur", "Mysuru", "T Narisipura", "Periyapatna", "H D Kote", "Saligrama", "Saraguru"],
  "Udupi": ["Baindur", "Karkala", "Kapu", "Udupi", "Hebri", "Kundapura", "Bhramhavara"],
  "Bagalkote": ["Bilagi", "Badami", "Mudhol", "Jamkhandi", "Hunagund", "Guledgudda", "Rabakavi-Banahatti", "Terdal", "Ilkal", "Bagalkote"],
  "Belagavi": ["Bailhongal", "Belagavi", "Soundathi", "Chikkodi", "Raibag", "Khanapur", "Ramdurg", "Hukkeri", "Athani", "Gokak", "Nippani", "Kagavada", "Mudalgi", "Yaragatti"],
  "Vijayapura": ["Sindgi", "Indi", "Muddebihal", "B Bagewadi", "Alamela", "Babaleshwar", "Nidagundi", "Vijayapura", "Tikota", "Chedachana", "Kolhar", "Devarahipparagi", "Talikote"],
  "Dharwad": ["Navalgund", "Dharwada", "Hubballi (U)", "Hubballi (R)", "Kalghatagi", "Kundaghol", "Annigeri", "Alnavar"],
  "Gadag": ["Mundargi", "Nargund", "Ron", "Shirahatti", "Gajendragad", "Lakshmeshwar", "Gadag"],
  "Haveri": ["Savanur", "Shiggaon", "Hirekerur", "Hanagal", "Ranebennur", "Byadagi", "Rattihalli", "Haveri"],
  "Uttara Kannada": ["Honnavar", "Sirsi", "Mundagod", "Yellapura", "Siddapura", "Haliyal", "Joida", "Bhatkal", "Ankola", "Kumta", "Dandeli", "Karwar"],
  "Ballari": ["Sandur", "Ballari", "Siraguppa", "Kurugodu", "Kampli"],
  "Bidar": ["Bhalki", "Bidar", "Humnabad", "Basava Kalyana", "Aurad", "Chitaguppa", "Hulusur", "Kamala Nagar"],
  "Kalaburagi": ["Afzalpur", "Kalaburagi", "Aland", "Jewargi", "Sedam", "Chittapur", "Chincholi", "Kalagi", "Kamalapur", "Yedrami", "Shahabad"],
  "Yadgiri": ["Yadgiri", "Shahapur", "Shorapur", "Hunasagi", "Vadagera", "Gurumitkal"],
  "Koppal": ["Kushtagi", "Yelburga", "Gangavathi", "Kukkunur", "Karatagi", "Kanakagiri", "Koppal"],
  "Raichur": ["Sindhanur", "Raichur", "Manvi", "Arakera", "Lingasugur", "Devadurga", "Maski", "Siravara"],
  "Vijayanagara": ["H B Halli", "Hospete", "Hadagali", "Kudligi", "Kottur", "Harappanahalli"]
};
