export const rajasthanData = {
    "Ajmer": ["Peesangan", "Pushkar", "Roopangarh", "Nasirabad", "Ajmer", "Kishangarh"],
    "Alwar": ["Rajgarh", "Ramgarh", "Reni", "Tehla", "Thanagazi", "Alwar", "Govindgarh", "Lachchmangarh", "Mala Khera", "Kathumar", "Nongawa"],
    "Balotra": ["Baytu", "Kalyanpur", "Pachpadra", "Gira", "Samdari", "Sindhari", "Siwana"],
    "Banswara": ["Abapura","Anandpuri","Arthuna","Bagidora","Chhoti Sarwan","Gangar Talai","Ganoda","Ghatol","Kushalgarh", "Sajjangarh"],
    "Baran": [ "Atru","Chhipabarod","Antah","Kishanganj","Mangrol","Chhabra","Shahabad"],
    "Barmer": ["Barmer", "Barmer Rural", "Chohtan", "Dhanau", "Gudha Malani", "Nokhda", "Dhorimana", "Gadra Road", "Ramsar", "Serwa", "Sheo"],
    "Beawar": ["Bijaynagar", "Raipur", "Badnor", "Todagarh", "Beawar", "Jaitaran"],
    "Bharatpur": ["Bhusawar", "Nadbai", "Uchchain", "Weir", "Bharatpur", "Bayana","Rupbas"],
    "Bhilwara": ["Mandalgarh", "Raipur", "Sahra", "Asind", "Beejoliya", "Karera", "Bhilwara", "Hameergarh", "Hurda", "Mandal"],
    "Bikaner": ["Bikaner", "Bajju", "Kolayat", "Chhatargarh", "Khajuwala", "Lunkaransar", "Nokha", "Pungal", "Sri Dungargarh"],
    "Bundi": ["Nainwa", "Indragarh", "Keshoraipatan", "Talera", "Hindoli",],
    "Chittorgarh": ["Badi Sadri", "Begun", "Bassi", "Chittorgarh", "Bhadesar", "Kapasan", "Bhoopal Sagar", "Nimbahera", "Dungla", "Rawatbhatia", "Gangrar", "Rashmi"],
    "Churu": ["Bhanipura", "Rajgarh", "Ratangarh", "Sardarshahar", "Sidhmukh", "Sujangarh", "Taranagar"],
    "Dausa": ["Bahravanda", "Baijuwada", "Bandikui", "Baswa", "Lalsot", "Lawaan", "Sikri", "Mahwa", "Mandawar", "Nangal Rajwatan", "Nirjharna", "Rahuvas", "Ramgarh Pachwara", "Senthil"],
    "Deeg": ["Deeg", "Kumher", "Maniya", "Pahadi", "Sikri","Kaman"],
    "Dholpur": ["Dholpur","Badi", "Maniya", "Baseri", "Rajakhera", "Sepau", "Sarmathura"],
    "Didwana Kuchaman": ["Didwana", "Kuchaman City", "Makrana", "Ladnu", "Maulasar", "Nava", "Parbatsar"],
    "Dudu": ["Mauzamabad", "Dudu"],
    "Dungarpur": ["Dovda", "Aspur", "Dungarpur", "Bichchiwara", "Gamdi Ahada", "Cheekhil", "Galiyakot", "Pal Deval", "Sabla", "Sagwara", "Simalwara"],
    //"Gangapur City": ["Talawada", "Todabhim", "Wazeerpur"],
    "Hanumangarh": ["Bhadra", "Nohar", "Rawatsar", "Sangaria", "Tibbi", "Hanumangarh"],
    "Jaipur": ["Amber","Jaipur","Kalwar", "Sanganer" ],
    //"Jaipur Rural": ["Madhora jpura", "Phulera (HQ Sambhar)", "Tunga"],
    "Jaisalmer": ["Bhaniyana", "Fatehgarh", "Jaisalmer", "Phalsund", "Sam", "Pokhran", "Ramgarh"],
    "Jalore": ["Bhingmal", "Ahore", "Bhadrajun", "Jalore", "Jaswantpur", "Sayla"],
    "Jhalawar": ["Aklera", "Asnawar", "Dug", "Bakani", "Gangdhar", "Jhalarpatan", "Khanpur", "Manohar Thana", "Panch Pahad", "Pidawa", "Sunel", "Raipur"],
    "Jhunjhunu": ["Jhunjhunu", "Bisau", "Buhana", "Gudha Gorji", "Nawalgarh", "Surajgarh"],
    "Jodhpur": ["Jodhpur","Pipar City", "Shekhaa", "Shergarh", "Tinwari", "Bilada", "Kudi Bhagtasani", "Bhopalgarh", "Baori", "Balesar", "Osian" ],
    "Karauli": ["Hindaun", "Mandrail", "Karauli", "Masalpur", "Shri Mahavari Ji", "Sapotara", "Suroth"],
    //
    "Kekri.": ["Sarwar", "Tantoti", "Totaraisingh", "Bhinay"],
    "KhairthalTijara": ["Kishangarh Bas", "Kotkasim", "Mundawar"],
    "Kota": ["Ramganj Mandi", "Sangod", "Pipalda"],
    "Kotputli Behror": ["Narayanpur", "Pavta", "Viratnagar"],
    "Nagaur": ["Deh", "Merta", "Mundwa", "Riyanbari", "Sanju"],
    "Neem Ka Thana": ["Patan", "Sri Madhpur", "Udaipurwati"],
    "Pali": ["Bali", "Marwar Junction"],
    "Phalodi": ["Bapini", "Dechu", "Lohawat", "Setrava"],
    "Pratapgarh": ["Dhanyawad", "Peepalkhoont", "Pratapgarh", "Suhagpura"],
    "Rajasmand": ["Deogarh", "Khamnor", "Kumbhalgarh", "Kunwariya", "Nathdwara", "Ra jasmand", "Railmagra"],
    "Salumbar": ["Salumbar", "Sarada", "Semari"],
    "Sanchore": ["Chitalwana", "Raniwara"],
    "Sawai Madhopur": ["Bamanwas", "Barnala", "Nadoti", "Gangapur City", "Gangapur", "Talawada", "Todabhim", "Wazeerpur", "Chauth Ka Barwara", "Khandar", "Mitrapura"],
    "Shahpura": ["Kotri", "Phooliyan Kalan"],
    //
    "Sikar": ["Khandela", "Lachmangarh", "Nechwa", "Ramgarh Shekhawati", "Sikar (Rural)"],
    "Sirohi": ["Deldar", "Pindwara", "Abu Road", "Sheoganj", "Reodar", "Sirohi"],
    "Anupgarh": ["Raisinghnagar", "Rawala", "Vijainagar","Anupgarh", "Rawala"],
    "Sri Ganganagar": ["Sadulshahar", "Sri Karapur", "Padampur", "Ganganagar", "Suratgarti"],
    "Tonk": ["Deoli", "Dooni", "Malpura", "Nagar Fort", "Peeplu", "Niwai", "Uniara", "Tonk"],
    "Udaipur": ["Badgaon", "Bhindar", "Girwa", "Gogunda", "Kanor", "Jhadol", "Kherwara", "Kuravad", "Mavli", "Naigaon", "Rishabdeo", "Vallabhnagar"],
};