export const rajasthanData = {
    "Ajmer": ["Peesangan", "Pushkar", "Roopangarh", "Nasirabad", "Ajmer", "Kishangarh"],
    "Alwar": ["Rajgarh", "Ramgarh", "Reni", "Tehla", "Thanagazi", "Alwar", "Govindgarh", "Lachchmangarh", "Mala Khera", "Kathumar", "Nongawa"],
    "Balotra": ["Baytu", "Kalyanpur", "Pachpadra", "Gira", "Samdari", "Sindhari", "Siwana"],
    "Banswara": ["Abapura","Anandpuri","Arthuna","Bagidora","Chhoti Sarwan","Gangar Talai","Ganoda","Ghatol","Kushalgarh", "Sajjangarh"],
    "Baran": [ "Atru","Chhipabarod","Antah","Kishanganj","Mangrol","Chhabra","Shahabad"],
    "Barmer": ["Barmer", "Barmer Rural", "Chohtan", "Dhanau", "Gudha Malani", "Nokhda", "Dhorimana", "Gadra Road", "Ramsar", "Serwa", "Sheo"],
    "Beawar": ["Bijaynagar", "Raipur", "Badnor", "Todagarh", "Beawar", "Jaitaran"],
    "Bharatpur": ["Bhusawar", "Nadbai", "Uchchain", "Weir"],
    "Bhilwara": ["Manda(garh", "Raipur", "Sahra"],
    "Bikaner": ["Lunkaransar", "Nokha", "Pungal", "Sri Dungargarh"],
    "Bundi": ["Nainwa", "lndragarh Keshoraipatan"],
    "Chittorgarh": ["Badi Sadri", "Bhoopal Sagar", "Dungla", "Gangrar", "Rashmi"],
    "Churu": ["Bhanipura", "Rajgarh", "Ratangarh", "Sardarshahar", "Sidhmukh", "Su jangarh", "Taranagar"],
    "Dausa": ["Mahwa", "Mandawar", "NangalRajwatan", "Nirjharna", "Rahuvas", "Ramgarh Pachwara", "Senthil"],
    "Deeg": ["Baseri", "Kumher", "Maniya", "Pahadi", "Sikri"],
    "Dholpur": ["Rajakhera", "Sepau"],
    "Didwana Kuchaman": ["Ladnu", "Maulasar", "Nava", "Parbatsar"],
    "Dudu": ["Mauzamabad", "Dudu"],
    "Dungarpur": ["Bichchiwara", "Cheekhil", "Dungarpur", "Galiyakot", "Gamdi Ahada", "Pal Deval", "Sabla", "Sagwara", "Simalwara"],
    "Gangapur City": ["Talawada", "Todabhim", "Wazeerpur"],
    "Hanumangarh": ["Sangaria", "Tibbi"],
    "Jaipur": ["Amber","Jaipur","Kalwar", "Sanganer" ],
    "Jaipur Rural": ["Madhora jpura", "Phulera (HQ Sambhar)", "Tunga"],
    "Jaisalmer": ["Phalsund", "Pokhran", "Ramgarh", "Sam"],
    "Jalore": ["Sayla", "jaswantpur"],
    "Jhalawar": ["Bakani", "Dug", "Gangdhar", "Jhalarpatan", "Khanpur", "Manohar Thana", "Panch Pahad", "Pidawa", "Raipur", "Sunel"],
    "Jhunj.hunu": ["Nawalgarh", "Surajgarh"],
    "Jodhpur": [],
    "Jodhpur Rural": ["PiparCity", "Shekhala", "Shergarh", "Tinwari"],
    "Karauli": ["Masalpur", "Sapotara", "Shri Mahavari Ji", "Suroth"],
    "Kekri.": ["Sarwar", "Tantoti", "Totaraisingh"],
    "KhairthalTijara": ["Kishangarh Bas", "Kotkasim", "Mundawar"],
    "Kota": [],
    "Kotput(i Behror": ["Narayanpur", "Pavta", "Viratnagar"],
    "Nagaur": ["Deh", "Merta", "Mundwa", "Riyanbari", "Sanju"],
    "Neem Ka Thana": ["Patan", "Sri Madhpur", "Udaipurwati"],
    "Pali": ["Bali", "Marwar Junction"],
    "Phalodi": ["Bapini", "Dechu", "Lohawat", "Setrava"],
    "Pratapgarh": ["Dhanyawad", "Peepalkhoont", "Pratapgarh", "Suhagpura"],
    "Rajasmand": ["Deogarh", "Khamnor", "Kumbhalgarh", "Kunwariya", "Nathdwara", "Ra jasmand", "Railmagra"],
    "Salumbar": ["Salumbar", "Sarada", "Semari"],
    "Sanchore": ["Chitalwana", "Raniwara"],
    "Sawai Madhopur": ["Chauth Ka Barwara", "Khandar", "Mitrapura"],
    "Shahpura": ["Kotri", "Phooliyan Kalan"],
    "Sikar": ["Khandela", "Lachmangarh", "Nechwa", "Ramgarh Shekhawati", "Sikar (Rural)"],
    "Sirohi": ["Reodar", "Sheoganj", "Sirohi"],
    "Anupgarh": ["Ra's'nghnagar", "Rawala", "Vijainagar"],
    "Sri Ganganagar": ["Sadulshahar", "Sri Karapur"],
    "Tonk": ["Nagar Fort", "Peeplu", "Uniara"],
    "Udaipur": ["Kherwara", "Kuravad", "Mavli", "Naigaon", "Rishabdeo", "Vallabhnagar"],
};